title: Koma's Home
email: komazhang@foxmail.com
description: >- # this means to ignore newlines until "baseurl:"
  家和万事兴，快乐编程  
baseurl: ""
github_username: KomaBeyond

permalink: pretty

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
